// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "CurrencyMetaDataSO", menuName = "SpecData/CurrencyMetaDataSO")]
public class CurrencyMetaDataSO : ScriptableObject
{
    public List<CurrencyMetaData> rows = new List<CurrencyMetaData>();
}
