// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;

/// <summary>
/// Config 시트 런타임 로더.
/// DataType 컬럼 기반으로 타입 안전한 조회 API를 제공합니다.
///
/// 사용 예시:
///   Managers.Config.GetInt(ConfigType.EventDay)    → 3
///   Managers.Config.GetFloat(ConfigType.JumpDelay) → 3.5f
///   Managers.Config.GetAuto(ConfigType.EventDay)   → (object)3
/// </summary>
public class ConfigManager
{
    public bool IsReady { get; private set; }

    struct ConfigEntry { public string DataType; public string Value; }

    readonly Dictionary<ConfigType, ConfigEntry> _dict =
        new Dictionary<ConfigType, ConfigEntry>();

    public IEnumerator CoDownloadConfig()
    {
        IsReady = false;
        Debug.Log("[ConfigManager] Config 다운로드 시작");

        string url = GoogleSheetConfig.BuildJsonUrl("Config");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[ConfigManager] Config 다운로드 실패: " + req.error);
                IsReady = true;
                yield break;
            }

            _dict.Clear();
            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 4);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    string dataType  = cells[1];
                    string configKey = cells[2];
                    string value     = cells[3];
                    if (!Enum.TryParse(configKey, true, out ConfigType key)) continue;
                    _dict[key] = new ConfigEntry { DataType = dataType, Value = value };
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[ConfigManager] 파싱 오류 row" + i + ": " + e.Message);
                }
            }

            Debug.Log("[ConfigManager] Config 로드 완료: " + _dict.Count + "개");
        }

        IsReady = true;
    }

    public int GetInt(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }

    public float GetFloat(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }

    public string GetString(ConfigType key) => GetRaw(key);

    public bool GetBool(ConfigType key)
    {
        string s = GetRaw(key);
        return s == "true" || s == "1" || s == "yes";
    }

    public long GetLong(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0L;
        if (s.Contains("."))
            return (long)double.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return long.Parse(s);
    }

    public double GetDouble(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0.0;
        return double.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }

    public decimal GetDecimal(ConfigType key)
    {
        string s = GetRaw(key);
        if (string.IsNullOrEmpty(s)) return 0m;
        return decimal.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }

    /// <summary>DataType 컬럼 기반으로 자동 파싱하여 반환합니다.</summary>
    public object GetAuto(ConfigType key)
    {
        if (!_dict.TryGetValue(key, out ConfigEntry entry)) return null;
        switch (entry.DataType)
        {
            case "int":    return GetInt(key);
            case "float":  return GetFloat(key);
            case "bool":   return GetBool(key);
            case "long":   return GetLong(key);
            case "double": return GetDouble(key);
            default:       return GetString(key);
        }
    }

    string GetRaw(ConfigType key) =>
        _dict.TryGetValue(key, out ConfigEntry e) ? e.Value : string.Empty;
}
