// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;

/// <summary>
/// Google Sheets JSON API를 런타임에 직접 호출하여 MetaData를 파싱합니다.
/// 빌드 후에도 시트 데이터 변경이 즉시 반영됩니다 (재빌드 불필요).
/// </summary>
public class SpecDataManager
{
    public bool IsReady { get; private set; }

    Dictionary<int, CurrencyMetaData> _currencyDict = new Dictionary<int, CurrencyMetaData>();
    List<CurrencyMetaData>            _currencyList = new List<CurrencyMetaData>();
    Dictionary<int, MonsterMetaData> _monsterDict = new Dictionary<int, MonsterMetaData>();
    List<MonsterMetaData>            _monsterList = new List<MonsterMetaData>();

    public IEnumerator CoDownloadDataSheet()
    {
        IsReady = false;
        Debug.Log("[SpecDataManager] 데이터 다운로드 시작");

        yield return CoFetch_Currency();
        yield return CoFetch_Monster();

        IsReady = true;
        Debug.Log("[SpecDataManager] 모든 데이터 로드 완료");
    }

    IEnumerator CoFetch_Currency()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Currency");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Currency 다운로드 실패: " + req.error);
                yield break;
            }

            _currencyDict.Clear();
            _currencyList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 2);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    CurrencyMetaData data = new CurrencyMetaData
                    {
                        Id = ParseInt(cells[0]),
                        CurrencyType = ParseEnum<CurrencyType>(cells[1]),
                    };
                    _currencyDict[data.Id] = data;
                    _currencyList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Currency 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Currency 로드 완료: " + _currencyList.Count + "개");
        }
    }

    IEnumerator CoFetch_Monster()
    {
        string url = GoogleSheetConfig.BuildJsonUrl("Monster");
        using (UnityWebRequest req = UnityWebRequest.Get(url))
        {
            yield return req.SendWebRequest();
            if (req.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[SpecDataManager] Monster 다운로드 실패: " + req.error);
                yield break;
            }

            _monsterDict.Clear();
            _monsterList.Clear();

            List<string[]> rows = GvizParser.Parse(req.downloadHandler.text, colCount: 10);
            for (int i = 2; i < rows.Count; i++)
            {
                string[] cells = rows[i];
                if (string.IsNullOrEmpty(cells[0])) continue;
                try
                {
                    MonsterMetaData data = new MonsterMetaData
                    {
                        Id = ParseInt(cells[0]),
                        MonsterType = ParseEnum<MonsterType>(cells[1]),
                        Level = ParseInt(cells[2]),
                        MaxHp = ParseFloat(cells[3]),
                        CommonAttackDamage = ParseFloat(cells[4]),
                        CommonAttackCoolTime = ParseFloat(cells[5]),
                        AttackRange = ParseFloat(cells[6]),
                        Defense = ParseFloat(cells[7]),
                        MoveSpeed = ParseFloat(cells[8]),
                        Gold = ParseInt(cells[9]),
                    };
                    _monsterDict[data.Id] = data;
                    _monsterList.Add(data);
                }
                catch (Exception e)
                {
                    Debug.LogWarning("[SpecDataManager] Monster 파싱 오류 row" + i + ": " + e.Message + " | " + string.Join(",", cells));
                }
            }

            Debug.Log("[SpecDataManager] Monster 로드 완료: " + _monsterList.Count + "개");
        }
    }

    public CurrencyMetaData GetCurrency(int id)
    {
        CurrencyMetaData result;
        _currencyDict.TryGetValue(id, out result);
        return result;
    }

    public List<CurrencyMetaData> GetAllCurrency()
    {
        return _currencyList;
    }

    public MonsterMetaData GetMonster(int id)
    {
        MonsterMetaData result;
        _monsterDict.TryGetValue(id, out result);
        return result;
    }

    public List<MonsterMetaData> GetAllMonster()
    {
        return _monsterList;
    }

    static int ParseInt(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0;
        if (s.Contains("."))
            return (int)float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        return int.Parse(s);
    }
    static float ParseFloat(string s)
    {
        if (string.IsNullOrEmpty(s)) return 0f;
        return float.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
    }
    static T ParseEnum<T>(string s) where T : struct
    {
        if (string.IsNullOrEmpty(s)) return default(T);
        return (T)Enum.Parse(typeof(T), s, true);
    }
}
