// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System.Collections.Generic;

/// <summary>
/// Google Sheets 연결 설정. SpecDataManager가 런타임에 참조합니다.
/// </summary>
public static class GoogleSheetConfig
{
    public const string SpreadsheetId = "15DaZH8xH5lCG-37xep0nZ66eFRW9H04uSKYgUccrtXo";

    public static readonly Dictionary<string, string> SheetGids =
        new Dictionary<string, string>
    {
        { "Currency", "0" },
        { "Monster", "1375711091" },
    };

    /// <summary>
    /// Google Visualization JSON API URL (공개 시트, API Key 불필요)
    /// 응답 형식: JSONP → JSONP 래퍼 제거 후 파싱
    /// </summary>
    public static string BuildJsonUrl(string gid)
    {
        return string.Format(
            "https://docs.google.com/spreadsheets/d/{0}/gviz/tq?tqx=out:json&gid={1}",
            SpreadsheetId, gid);
    }
}
