// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================
using System;

// 모든 MetaData 클래스는 이 파일에서 통합 관리합니다.
// 컬럼 구조가 바뀌면 에디터 툴을 재실행하세요.

// ── Currency ─────────────────────────────────────────
[Serializable]
public class CurrencyMetaData
{
    public int Id;
    public CurrencyType CurrencyType;
}

// ── Monster ─────────────────────────────────────────
[Serializable]
public class MonsterMetaData
{
    public int Id;
    public MonsterType MonsterType;
    public int Level;
    public float MaxHp;
    public float CommonAttackDamage;
    public float CommonAttackCoolTime;
    public float AttackRange;
    public float Defense;
    public float MoveSpeed;
    public int Gold;
}
