// ============================================================
// Auto-generated by GoogleSheetCodeGenerator.
// Do NOT edit manually — 컬럼 구조 변경 시 툴을 재실행하세요.
// ============================================================

public enum CurrencyType
{
    None = 0,
    Gold,
    Jewel,
    Exp,
    Level,
}

public enum MonsterType
{
    None = 0,
    Bear,
}

public enum ConfigType
{
    None = 0,
    EventDay,
    JumpDelay,
    StartWord,
    TestWord,
}

